name: rail_sub_menu
description: Flutter M3 Rail Submenu demo project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  go_router: ^5.2.4
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  sprung: ^3.0.1
  nanoid: ^1.0.0
  fluentui_system_icons: ^1.1.189
  google_fonts: ^3.0.1
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  riverpod_generator: ^1.1.1


flutter:
  uses-material-design: true


